# Generated by Django 5.2.7 on 2025-10-29 11:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_schedule_useractivity_userattribute_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userattribute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userrelationship',
            options={},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='userattribute',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='details',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='character_emotion',
            field=models.CharField(blank=True, help_text='AI 캐릭터의 감정 상태', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='메시지에 첨부된 이미지 파일', null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='activity_date',
            field=models.DateField(blank=True, help_text='활동 날짜', null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='activity_time',
            field=models.TimeField(blank=True, help_text='활동 시간', null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='companion',
            field=models.CharField(blank=True, help_text='동행인', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='memo',
            field=models.TextField(blank=True, help_text='활동 관련 메모 또는 대화 내용', null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='place',
            field=models.CharField(blank=True, help_text='장소', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, 
                default=datetime.datetime(2023, 1, 1, 0, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memory',
            field=models.JSONField(default=dict, help_text='사용자에 대한 기억 저장소'),
        ),
        migrations.AddField(
            model_name='userrelationship',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, 
                default=datetime.datetime(2023, 1, 1, 0, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrelationship',
            name='disambiguator',
            field=models.CharField(blank=True, help_text="동명이인 구분을 위한 식별자 (예: '개발팀', '친구')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='content',
            field=models.CharField(blank=True, help_text="속성 내용 (예: '털털함', 'INFP', '1995-10-31')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='fact_type',
            field=models.CharField(blank=True, help_text="속성의 종류 (예: '성격', 'MBTI', '생일')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='affinity_score',
            field=models.IntegerField(default=0, help_text="AI '아이'와의 호감도 점수"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chatbot_name',
            field=models.CharField(default='아이', help_text='사용자가 지정한 챗봇 이름', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_onboarding_complete',
            field=models.BooleanField(default=False, help_text='사용자 초기 설정(온보딩) 완료 여부'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='name',
            field=models.CharField(help_text='상대방 이름', max_length=100),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='position',
            field=models.CharField(blank=True, help_text='관계 내 포지션 (예: 오빠, 친한 친구, 상사)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='relationship_type',
            field=models.CharField(help_text='관계 유형 (예: 가족, 친구, 직장 동료)', max_length=100),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='serial_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='동일 인물 구분을 위한 고유 시리얼 코드', unique=True),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='traits',
            field=models.TextField(blank=True, help_text='상대방 성격 또는 특징', null=True),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userattribute',
            unique_together={('user', 'fact_type', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='userrelationship',
            unique_together={('user', 'serial_code')},
        ),
        migrations.CreateModel(
            name='ActivityAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', '주간'), ('monthly', '월간'), ('yearly', '연간')], max_length=10)),
                ('period_start_date', models.DateField(help_text='통계 기간의 시작일')),
                ('place', models.CharField(db_index=True, help_text='장소', max_length=255)),
                ('companion', models.CharField(blank=True, db_index=True, help_text='동행인', max_length=255, null=True)),
                ('count', models.PositiveIntegerField(default=0, help_text='해당 기간 동안의 방문 횟수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'period_type', 'period_start_date', 'place', 'companion')},
            },
        ),
        migrations.CreateModel(
            name='PendingProactiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.chatmessage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_proactive_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('all', '랜덤'), ('korean_history', '한국사'), ('world_history', '세계사'), ('science', '과학'), ('literature', '문학'), ('general', '상식')], help_text='퀴즈 장르', max_length=100)),
                ('num_questions', models.IntegerField(help_text='총 문제 수')),
                ('score', models.IntegerField(help_text='획득 점수')),
                ('date_completed', models.DateTimeField(auto_now_add=True, help_text='퀴즈 완료 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_completed'],
            },
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='일과 날짜')),
                ('schedule_time', models.TimeField(blank=True, help_text='일과 시간', null=True)),
                ('content', models.TextField(blank=True, help_text='하루 일과 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', '-schedule_time'],
            },
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
